---
openapi: 3.0.0
info:
  title: 상품 관리 API
  description: "상품을 등록, 조회, 수정, 삭제하는 API입니다."
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/PachyuChepe/testAPI/1.0.0
  description: SwaggerHub API Auto Mocking
- url: http://aws-node-project.kro.kr/
  description: HTTP 배포 주소
- url: https://node-solo-lv1.kro.kr
  description: HTTPS(?) 배포 주소
- url: http://localhost:3000
  description: 로컬 개발 서버 주소
tags:
- name: Products
  description: 상품 관련 엔드포인트
paths:
  /api/products:
    get:
      tags:
      - Products
      summary: 상품 목록 조회
      responses:
        "200":
          description: 상품 목록을 성공적으로 조회했습니다.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "500":
          description: 상품 목록 조회에 실패하였습니다.
  /api/product:
    post:
      tags:
      - Products
      summary: 상품 등록
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api_product_body'
      responses:
        "201":
          description: 판매 상품을 등록하였습니다.
        "400":
          description: 데이터 형식이 올바르지 않습니다.
        "500":
          description: 서버에서 오류가 발생하였습니다.
  /api/product/{userItemId}:
    get:
      tags:
      - Products
      summary: 상품 상세 조회
      parameters:
      - name: userItemId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: 상품 상세 정보를 조회했습니다.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "404":
          description: 상품이 존재하지 않습니다.
        "500":
          description: 서버에서 오류가 발생하였습니다.
    put:
      tags:
      - Products
      summary: 상품 정보 수정
      parameters:
      - name: userItemId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/product_userItemId_body'
      responses:
        "200":
          description: 상품 정보를 수정하였습니다.
        "400":
          description: 데이터 형식이 올바르지 않습니다.
        "401":
          description: 상품을 수정할 권한이 없습니다.
        "404":
          description: 상품 조회에 실패했습니다.
        "500":
          description: 서버에서 오류가 발생하였습니다.
    delete:
      tags:
      - Products
      summary: 상품 삭제
      parameters:
      - name: userItemId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/product_userItemId_body_1'
      responses:
        "200":
          description: 상품을 삭제하였습니다.
        "401":
          description: 상품을 삭제할 권한이 없습니다.
        "404":
          description: 상품 조회에 실패했습니다.
        "500":
          description: 서버에서 오류가 발생하였습니다.
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              _id:
                type: string
              title:
                type: string
              author:
                type: string
              status:
                type: string
              createdAt:
                type: string
    api_product_body:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        author:
          type: string
        password:
          type: string
        status:
          type: string
    inline_response_200_1:
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
        content:
          type: string
        author:
          type: string
        status:
          type: string
        createdAt:
          type: string
    product_userItemId_body:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        author:
          type: string
        password:
          type: string
        status:
          type: string
    product_userItemId_body_1:
      type: object
      properties:
        password:
          type: string
